### ISSUE TITLE
media-codec / cedar released as LGPL, but where is the source?

### ISSUE THREAD

**Issue by oliv3r** [allwinner-zh/media-codec#5]
Having the whole media-codec under LGPL is stil good for 3rd parties however, as can be seen in allwinner-zh/media-codec-lib#1 the media-codec-lib is still infringing on the GPL.

**Comment by allwinner-zh** [comment]
No, there is none GPL issues in the media-codec-lib.
Please provide the evidence to me.

**Comment by ghost** [comment]
https://linux-sunxi.org/GPL_Violations
